### ISSUE TITLE
Gerrit trigger can't post sonarqube report

### ISSUE THREAD

**Issue by ChenJianHong2025** [aquarellian/sonar-gerrit-plugin#23]
I am integrating sonarqube  with gerrit. After running my Jenkins job Gerrit trigger throw this error.   My Gerrit connection type is HTTP, gerrit trigger configuration is REST API.
Gerrit trigger version: 2.29.0.

> 
> 17:54:01.564 DEBUG: Execution getVersion
> 17:54:01.564 DEBUG: Execution stop
> WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
> Getting Sonar Report from: /var/lib/jenkins/workspace/test-project1/.scannerwork/sonar-report.json
> Report has loaded and contains 1 issues
> Issues to be commented: 0
> Issues to be involved in score calculation: 0
> ERROR: Step ‘Post SonarQube issues as Gerrit comments’ failed: Unable to post review: Request not successful. Message: HTTP method POST is not supported by this URL. Status-Code: 405. Content: HTTP method POST is not supported by this URL.
> ERROR Gerrit response: HTTP method POST is not supported by this URLFinished: FAILURE

I browsed on web and tried so many methods but still no way. Can you help to figure it out?

**Comment by Chenguoqing2008** [comment]
I have added the logger in Jenkins to trace result. The complete log is here:

> 
> Aug 15, 2019 9:24:21 AM INFO org.jenkinsci.plugins.sonargerrit.TaskListenerLogger logMessage
> 
> Issues to be commented: 0
> 
> Aug 15, 2019 9:24:21 AM INFO org.jenkinsci.plugins.sonargerrit.TaskListenerLogger logMessage
> 
> Issues to be involved in score calculation: 0
> 
> Aug 15, 2019 9:24:21 AM SEVERE org.jenkinsci.plugins.sonargerrit.SonarToGerritPublisher perform
> 
> Unable to post review: Request not successful. Message: HTTP method POST is not supported by this URL. Status-Code: 405. Content: HTTP method POST is not supported by this URL.
> com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: HTTP method POST is not supported by this URL. Status-Code: 405. Content: HTTP method POST is not supported by this URL.
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.throwHttpStatusException(GerritRestClient.java:467)
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkStatusCodeError(GerritRestClient.java:454)
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkStatusCodeClientError(GerritRestClient.java:440)
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkStatusCode(GerritRestClient.java:432)
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:227)
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestRest(GerritRestClient.java:163)
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestRest(GerritRestClient.java:155)
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestJson(GerritRestClient.java:132)
> 	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.postRequest(GerritRestClient.java:111)
> 	at com.urswolfer.gerrit.client.rest.http.changes.RevisionApiRestClient.review(RevisionApiRestClient.java:78)
> 	at org.jenkinsci.plugins.sonargerrit.review.GerritRevisionWrapper.sendReview(GerritRevisionWrapper.java:43)
> 	at org.jenkinsci.plugins.sonargerrit.SonarToGerritPublisher.perform(SonarToGerritPublisher.java:146)
> 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
> 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
> 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
> 	at hudson.model.Run.execute(Run.java:1843)
> 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
> 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 	at hudson.model.Executor.run(Executor.java:429)
>

**Comment by ChenJianHong2025** [comment]
Closing this issue for traced at another comment. 
[https://github.com/tech-advantage/sonar-gerrit-plugin/issues/66](url)
